#!/usr/bin/env python3
"""
Generate version header file from git information
"""

import subprocess
import sys
import os
from datetime import datetime

def run_git_command(cmd):
    """Run a git command and return the output"""
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=os.getcwd())
        if result.returncode == 0:
            return result.stdout.strip()
        return None
    except Exception:
        return None

def get_version_info():
    """Extract version information from git"""
    
    # Try to get exact tag on current commit
    git_tag = run_git_command("git describe --tags --exact-match 2>/dev/null")
    
    if git_tag:
        # Current commit is tagged
        version = git_tag
        is_dev = False
    else:
        # Get latest tag
        latest_tag = run_git_command("git describe --tags --abbrev=0 2>/dev/null")
        
        if latest_tag:
            # Count commits since latest tag
            commit_count = run_git_command(f"git rev-list {latest_tag}..HEAD --count")
            if commit_count and int(commit_count) > 0:
                version = f"{latest_tag}-dev+{commit_count}"
                is_dev = True
            else:
                version = latest_tag
                is_dev = False
        else:
            # No tags found, use date-based version
            version = datetime.now().strftime("%Y%m%d-%H%M%S")
            is_dev = True
    
    # Get commit hash
    commit_hash = run_git_command("git rev-parse --short HEAD")
    if not commit_hash:
        commit_hash = "unknown"
    
    # Get build timestamp
    build_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    
    return {
        'version': version,
        'commit_hash': commit_hash,
        'build_time': build_time,
        'is_dev': is_dev
    }

def generate_version_header(output_file):
    """Generate version.h header file"""
    
    version_info = get_version_info()
    
    header_content = f'''#ifndef VERSION_H
#define VERSION_H

// Auto-generated version information
// Do not edit this file manually

#define FIRMWARE_VERSION "{version_info['version']}"
#define FIRMWARE_COMMIT "{version_info['commit_hash']}"
#define FIRMWARE_BUILD_TIME "{version_info['build_time']}"
#define FIRMWARE_IS_DEV {str(version_info['is_dev']).lower()}

// Version components for OTA manager
#define VERSION_STRING FIRMWARE_VERSION
#define BUILD_INFO FIRMWARE_VERSION " (" FIRMWARE_COMMIT ")"

#endif // VERSION_H
'''
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    # Write header file
    with open(output_file, 'w') as f:
        f.write(header_content)
    
    print(f"Generated version header: {output_file}")
    print(f"Version: {version_info['version']}")
    print(f"Commit: {version_info['commit_hash']}")
    print(f"Build time: {version_info['build_time']}")
    print(f"Development build: {version_info['is_dev']}")
    
    return version_info

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: generate_version.py <output_file>")
        sys.exit(1)
    
    output_file = sys.argv[1]
    generate_version_header(output_file)